### ISSUE TITLE
fp-idx build and run problems

### ISSUE THREAD

**Issue by tantrev** [johnmay/efficient-bits#1]
Hello!  I've been trying to get your fp-idx programs running and have run into a couple of build problems:

1. The "pom.xml" file seems to reference versions of "2.0-SNAPSHOT" modules that no longer exist.  I've been able to get these errors rectified by changing the versions to just "2.0".
2. The "make-stubs.sh" seems to reference several stub files that no longer exist.  It seems these errors can be safely ignored.

Most importantly though, when I try directly running the "java -cp target/nfp.jar org.openscience.cdk.nfp.SimSearch" command with an index file, the following error is returned:

```
Exception in thread "main" java.lang.NullPointerException
	at org.openscience.cdk.nfp.SimilarityIndex.top(SimilarityIndex.java:103)
	at org.openscience.cdk.nfp.SimSearch.main(SimSearch.java:172)
```

Any idea what I'm doing wrong?  I'm sure it's something painfully obvious.  Thank you in advance.

**Comment by tantrev** [comment]
Nevermind, I figured it out. 👍  I just had to specify "-idx" and "-min" for the "java -cp target/nfp.jar org.openscience.cdk.nfp.SimSearch" command.  Silly me!
